# Generated by Django 5.0.3 on 2024-04-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_orderplaced_status_alter_product_category_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='user',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Way', 'On The Way'), ('Packed', 'Packed'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MC', 'metalCraft'), ('PC', 'paintingCraft'), ('BC', 'bambooCraft'), ('JC', 'juteCraft')], max_length=2),
        ),
    ]
