# Generated by Django 5.0.6 on 2024-05-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_name_shop_username_remove_shop_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='customer',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('On The Way', 'On The Way'), ('Cancel', 'Cancel'), ('Packed', 'Packed'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BC', 'bambooCraft'), ('MC', 'metalCraft'), ('JC', 'juteCraft'), ('PC', 'paintingCraft')], max_length=2),
        ),
    ]
