# Generated by Django 5.0.6 on 2024-05-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_orderplaced_customer_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PC', 'paintingCraft'), ('JC', 'juteCraft'), ('BC', 'bambooCraft'), ('MC', 'metalCraft')], max_length=2),
        ),
    ]
