# Generated by Django 5.0.6 on 2024-05-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profile_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Way', 'On The Way'), ('Packed', 'Packed'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BC', 'bambooCraft'), ('JC', 'juteCraft'), ('PC', 'paintingCraft'), ('MC', 'metalCraft')], max_length=2),
        ),
    ]
