# Generated by Django 5.0.6 on 2024-05-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_orderplaced_status_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='shopname',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('On The Way', 'On The Way'), ('Accepted', 'Accepted'), ('Packed', 'Packed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BC', 'bambooCraft'), ('MC', 'metalCraft'), ('JC', 'juteCraft'), ('PC', 'paintingCraft')], max_length=2),
        ),
    ]
