# Generated by Django 5.0.6 on 2024-05-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_profile_shopname_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='dob',
            new_name='dob1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='gender',
            new_name='gender1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='username1',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Packed', 'Packed'), ('Delivered', 'Delivered'), ('On The Way', 'On The Way'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MC', 'metalCraft'), ('BC', 'bambooCraft'), ('PC', 'paintingCraft'), ('JC', 'juteCraft')], max_length=2),
        ),
    ]
