# Generated by Django 5.0.6 on 2024-05-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_profile_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Way', 'On The Way'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Packed', 'Packed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PC', 'paintingCraft'), ('JC', 'juteCraft'), ('MC', 'metalCraft'), ('BC', 'bambooCraft')], max_length=2),
        ),
    ]
